# PipeGen Configuration for Confluent Cloud
# Cloud deployment mode
local_mode: false

# Kafka Configuration (Confluent Cloud)
bootstrap_servers: "your-bootstrap-server.confluent.cloud:9092"
api_key: "YOUR_API_KEY"
api_secret: "YOUR_API_SECRET"

# FlinkSQL Configuration (Confluent Cloud)
flink_api_key: "YOUR_FLINK_API_KEY"
flink_api_secret: "YOUR_FLINK_API_SECRET"
flink_environment: "YOUR_FLINK_ENVIRONMENT_ID"
flink_compute_pool: "YOUR_FLINK_COMPUTE_POOL_ID"

# Schema Registry Configuration (Confluent Cloud)
schema_registry_url: "https://your-schema-registry.confluent.cloud"
schema_registry_key: "YOUR_SCHEMA_REGISTRY_KEY"
schema_registry_secret: "YOUR_SCHEMA_REGISTRY_SECRET"

# Pipeline Configuration
default_message_rate: 100
default_duration: "5m"
topic_prefix: "{{.ProjectName}}"
cleanup_on_exit: true
