# PipeGen Configuration for Local Development
# Local development mode
local_mode: true

# Kafka Configuration (local) - Host machine access
bootstrap_servers: "localhost:9093"

# FlinkSQL Configuration (local)
flink_url: "http://localhost:8081"

# Schema Registry Configuration (local)
schema_registry_url: "http://localhost:8082"

# Pipeline Configuration
default_message_rate: 100
default_duration: "5m"
topic_prefix: "{{.ProjectName}}"
cleanup_on_exit: true

# Kafka Configuration for local development
kafka_config:
  partitions: 1                # Default partitions for new topics (reduced for local)
  replication_factor: 1        # Replication factor (1 for single broker)
  retention_ms: 604800000      # 7 days retention

producer_config:
  compression_type: "snappy"   # Message compression
  batch_size: 16384           # Batch size in bytes
  linger_ms: 5                # Batching delay

consumer_config:
  session_timeout_ms: 30000   # Consumer session timeout
  heartbeat_interval_ms: 3000 # Consumer heartbeat interval
  max_poll_records: 500       # Max records per poll
  auto_offset_reset: "earliest" # Start from beginning for new groups

# Dashboard Configuration
dashboard_auto_open: false    # Don't auto-open browser in CI/testing
